using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("ELW.Library.Math")]
[assembly: AssemblyDescriptionAttribute("Library for manipilations with expression.")]
[assembly: AssemblyCompanyAttribute("Elwood Home")]
[assembly: AssemblyConfigurationAttribute("net-3.5 release")]
[assembly: AssemblyVersionAttribute("0.1.0.2")]

